# Generated by Django 3.1.5 on 2021-03-17 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytoken',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
