# Generated by Django 3.1.5 on 2021-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20210317_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytoken',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paytoken',
            name='apikey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paytoken',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paytoken',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
