# Generated by Django 3.1.5 on 2021-03-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20210317_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytoken',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
