  
version: '3.3'
services: 
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    volumes: 
      - .:/app
    depends_on: 
      - db

  
  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: payment
      MYSQL_USER: payment
      MYSQL_PASSWORD: payment
      MYSQL_ROOT_PASSWORD: payment
    volumes: 
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306