# Generated by Django 3.1.5 on 2021-03-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchantkey',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pins',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='mobile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
