# Generated by Django 3.1.5 on 2021-01-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_log_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('variation_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('variation_amount', models.FloatField()),
            ],
            options={
                'db_table': 'utility',
            },
        ),
    ]
