# Generated by Django 3.1.5 on 2021-02-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
