# Generated by Django 3.1.5 on 2021-02-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210204_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
