# Generated by Django 3.1.5 on 2021-02-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210204_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='EToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('token', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'e_token',
            },
        ),
    ]
