# Generated by Django 3.1.5 on 2021-02-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_etoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='etoken',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
