# Generated by Django 3.1.5 on 2021-03-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210309_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.TextField(blank=True, null=True, verbose_name='fullname'),
        ),
    ]
