# Generated by Django 3.1.5 on 2021-03-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('bus_name', models.TextField(blank=True, null=True)),
                ('bus_address', models.TextField(blank=True, null=True)),
                ('callbackurl', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
        migrations.CreateModel(
            name='MerchantKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(blank=True, null=True)),
                ('live_key', models.TextField(blank=True, null=True)),
                ('test_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'merchant_key',
            },
        ),
    ]
